// <auto-generated />
using System;
using Final_Project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Final_Project.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21");

            modelBuilder.Entity("Final_Project.Models.Streamer", b =>
                {
                    b.Property<int>("StreamerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MainGame")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("VOD")
                        .HasColumnType("TEXT");

                    b.HasKey("StreamerId");

                    b.ToTable("Streamer");
                });

            modelBuilder.Entity("Final_Project.Models.VideoGame", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvgCompletionTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvgRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("price")
                        .HasColumnType("TEXT");

                    b.HasKey("GameId");

                    b.ToTable("VideoGame");
                });

            modelBuilder.Entity("Final_Project.Models.VideoGameStreamer", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StreamerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VideoGameGameId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId", "StreamerId");

                    b.HasIndex("StreamerId");

                    b.HasIndex("VideoGameGameId");

                    b.ToTable("VideoGameStreamer");
                });

            modelBuilder.Entity("Final_Project.Models.VideoGameStreamer", b =>
                {
                    b.HasOne("Final_Project.Models.Streamer", "Streamer")
                        .WithMany("VideoGameStreamers")
                        .HasForeignKey("StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Final_Project.Models.VideoGame", "VideoGame")
                        .WithMany()
                        .HasForeignKey("VideoGameGameId");
                });
#pragma warning restore 612, 618
        }
    }
}
